version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    # environment:
    #   - NODE_ENV=development
